# Generated by Django 2.0.5 on 2020-04-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNetworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(default='', max_length=200)),
                ('representantes', models.CharField(default='', max_length=200)),
                ('presence_online', models.CharField(default='', max_length=200)),
                ('fecha_company', models.CharField(default='', max_length=200)),
                ('tamano_company', models.CharField(default='', max_length=200)),
                ('uri_reporte_tech', models.CharField(default='', max_length=200)),
                ('uri_reporte_linkedin', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('tlf_contacto', models.CharField(default='', max_length=200)),
                ('emails', models.CharField(default='', max_length=200)),
                ('website_posible', models.CharField(default='', max_length=200)),
                ('top_sites', models.CharField(default='', max_length=200)),
                ('fanpage_fb', models.CharField(default='', max_length=200)),
                ('web_server', models.CharField(default='', max_length=200)),
                ('web_framework', models.CharField(default='', max_length=200)),
                ('js_framework', models.CharField(default='', max_length=200)),
                ('cms', models.CharField(default='', max_length=200)),
                ('number_employers', models.CharField(default='', max_length=200)),
                ('ruc', models.CharField(default='', max_length=200, unique=True)),
                ('rubro', models.CharField(default='', max_length=200)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('programming_languaje', models.CharField(default='', max_length=200)),
                ('company_status', models.CharField(default='', max_length=200)),
                ('twiter_page', models.CharField(default='', max_length=200)),
                ('all_tech', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
